# Generated by Django 4.0.4 on 2022-05-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restauranttimeslot_restaurants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restauranttimeslot",
            old_name="restaurants",
            new_name="restaurant",
        ),
    ]
