# Generated by Django 4.0.4 on 2022-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restauranttimeslot_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restauranttimeslot',
            unique_together={('restaurant', 'day', 'opening_hour', 'closing_hour')},
        ),
    ]
