# Generated by Django 4.0.4 on 2022-05-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menu_name_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
    ]
