# Generated by Django 4.0.4 on 2022-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasehistory",
            old_name="users",
            new_name="user",
        ),
    ]
